title: https://www.open-ost.ch/
description: > # this means to ignore newlines until "baseurl:"
  Wir fördern die Open Source Community und unterstützen dich bei
  der Benutzung deines alternativen Betriebssystems an der OST.
baseurl: ""
url: "https://www.open-ost.ch/" # the base hostname & protocol for your site

github_username: openost
git_repo: www.open-ost.ch

exclude:
  - docker/
  - Makefile
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - wercker.yml
  - vendor
  - .bundle
  - tmp

host: 0.0.0.0

markdown: kramdown
highlighter: rouge

plugins:
  - jemoji
  - jekyll-redirect-from

emoji:
  src: "/assets"

# The documentation parts are stored as collections;
# that means, they are just a somewhat special page.
collections:
  hsr:
    output: true
  app:
    output: true
  events:
    output: true

defaults:
  - scope: # content pages
      path: "tipps"
      type: "posts"
    values:
      layout: "page"
      permalink: /:categories/:title/
  - scope: # content pages
      path: "pages"
    values:
      layout: "page"
      permalink: /:basename/
  - scope: # hsr collection
      type: hsr
      path: ""
    values:
      layout: "hsr"
      permalink: /hsr/:slug/
  - scope: # app collection
      type: app
      path: ""
    values:
      layout: "app"
      permalink: /app/:slug/
  - scope: # events
      type: events
      path: ""
    values:
      layout: "events"
      permalink: /events/:slug/
